### ISSUE TITLE
Consider adding selinux policy?

### ISSUE THREAD

**Issue by croepha** [sameersbn/docker-nginx#3]
I am not even sure if this is a good idea, as I really dont understand what the attached selinux policy is supposed to do, or why it isn't default on my setup (Fedora Server)  but with selinux I was getting some weird errors:

```
nginx: [error] [ngx_pagespeed 1.9.32.10-7423] Unable to create SHM segment [1]globalstatistics, mmap failed with errno=13.
nginx: [warn] [ngx_pagespeed 1.9.32.10-7423] Problem during shared memory setup; statistics functionality unavailable.
nginx: [error] [ngx_pagespeed 1.9.32.10-7423] Unable to create SHM segment [1]dummy_hostname:-1statistics, mmap failed with errno=13.
nginx: [warn] [ngx_pagespeed 1.9.32.10-7423] Problem during shared memory setup; statistics functionality unavailable.
nginx: [error] [ngx_pagespeed 1.9.32.10-7423] Unable to create SHM segment [1]pagespeed_default_shm/metadata_cache, mmap failed with errno=13.
nginx: [error] [ngx_pagespeed 1.9.32.10-7423] SharedMemCache: can't create segment pagespeed_default_shm/metadata_cache of size 52445184
nginx: [error] [ngx_pagespeed 1.9.32.10-7423] Unable to create SHM segment [1]/named_locks, mmap failed with errno=13.
nginx: [error] [ngx_pagespeed 1.9.32.10-7423] Unable to create memory segment for locks.
```

This selinux policy will silence the error, and allow you to use selinux:

```
module sameersbn-docker-nginx 1.0;

require {
    type svirt_lxc_net_t;
    type svirt_sandbox_file_t;
    class chr_file execute;
}

#============= svirt_lxc_net_t ==============

#!!!! The file '/dev/zero' is mislabeled on your system.
#!!!! Fix with $ restorecon -R -v /dev/zero
allow svirt_lxc_net_t svirt_sandbox_file_t:chr_file execute;
```

I save that file as `sameersbn-docker-nginx.te`
Then run these commands:

```
checkmodule -M -m -o sameersbn-docker-nginx.mod sameersbn-docker-nginx.te
semodule_package -o sameersbn-docker-nginx.pp -m sameersbn-docker-nginx.mod
sudo semodule -i sameersbn-docker-nginx.pp
```

Anyway, that might be an easy workaround for some people still wanting to use selinux...

Again, I really dont understand that this policy is doing, and what it has to do with shared memory, I went ahead and tried a generic mmap test (https://gist.github.com/kashyapp/4385922#file-mmap-fork-c)  in this with this docker image and selinux enabled, and it worked with no problem,  The only reason I used this policy is because it was generated with audit2allow, so it may be phony or incorrect or missing the bigger picture.... but I figured this might help someone, if you think this is out of scope, then i'll close

**Comment by croepha** [comment]
Update: so it looks like its using mmap on /dev/zero for anonymous memory, which requires execute permissions

**Comment by croepha** [comment]
I asked on #seliniux on freenode, and it looks like `allow svirt_lxc_net_t svirt_sandbox_file_t:chr_file execute;` is perfectly fine

**Comment by sameersbn** [comment]
should we distribute this in the git repo?

**Comment by croepha** [comment]
Yes, thats what I would recommend, do you want me to do a pr?

**Comment by sameersbn** [comment]
Yes, that would be great. Create a folder named `support/selinux/` for 
the policy file and maybe a README with the instructions. What do you think?

On Thursday 04 February 2016 10:25 PM, David Butler wrote:

> Yes, thats what I would recommend, do you want me to do a pr?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sameersbn/docker-nginx/issues/3#issuecomment-179944205.

## 

Sameer Naik

w: http://www.damagehead.com e: sameer@damagehead.com

**Comment by croepha** [comment]
sounds good, ill, hack on that after a bit
